# Generated by Django 4.2.23 on 2025-07-21 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('idanimal', models.IntegerField(db_column='idAnimal', primary_key=True, serialize=False)),
                ('especie', models.CharField(blank=True, max_length=100, null=True)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.CharField(blank=True, max_length=50, null=True)),
                ('fechanacimiento', models.DateField(blank=True, db_column='fechaNacimiento', null=True)),
                ('imagen', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'animal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('idfinca', models.AutoField(db_column='idFinca', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('latitud', models.IntegerField(blank=True, null=True)),
                ('longitud', models.IntegerField(blank=True, null=True)),
                ('hectareas', models.IntegerField(blank=True, null=True)),
                ('fuenteagua', models.CharField(blank=True, db_column='fuenteAgua', max_length=100, null=True)),
                ('explotacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idhorario', models.AutoField(db_column='idHorario', primary_key=True, serialize=False)),
                ('diasemana', models.CharField(blank=True, db_column='diaSemana', max_length=50, null=True)),
                ('horainicio', models.TimeField(blank=True, db_column='horaInicio', null=True)),
                ('horafin', models.TimeField(blank=True, db_column='horaFin', null=True)),
            ],
            options={
                'db_table': 'horario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('idmadre', models.IntegerField(db_column='idMadre', primary_key=True, serialize=False)),
                ('especie', models.CharField(blank=True, max_length=100, null=True)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'madre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('idpadre', models.IntegerField(db_column='idPadre', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('especie', models.CharField(blank=True, max_length=100, null=True)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'padre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('cedulapropietario', models.IntegerField(db_column='cedulaPropietario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=13, null=True)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'propietario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('contrasena', models.CharField(blank=True, max_length=100, null=True)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('idtrazabilidad', models.AutoField(db_column='idTrazabilidad', primary_key=True, serialize=False)),
                ('tipoevento', models.CharField(blank=True, db_column='tipoEvento', max_length=100, null=True)),
                ('fechaevento', models.DateField(blank=True, db_column='fechaEvento', null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('idanimal', models.ForeignKey(blank=True, db_column='idAnimal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.animal')),
            ],
            options={
                'db_table': 'trazabilidad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Registrosalud',
            fields=[
                ('idsalud', models.AutoField(db_column='idSalud', primary_key=True, serialize=False)),
                ('tipotratamiento', models.CharField(blank=True, db_column='tipoTratamiento', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('idanimal', models.ForeignKey(blank=True, db_column='idAnimal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.animal')),
            ],
            options={
                'db_table': 'registrosalud',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Registroreproduccion',
            fields=[
                ('idreproduccion', models.AutoField(db_column='idReproduccion', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipoevento', models.CharField(blank=True, db_column='tipoEvento', max_length=100, null=True)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('idanimal', models.ForeignKey(blank=True, db_column='idAnimal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.animal')),
            ],
            options={
                'db_table': 'registroreproduccion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Registroproduccion',
            fields=[
                ('idproduccion', models.AutoField(db_column='idProduccion', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipoproducto', models.CharField(blank=True, db_column='tipoProducto', max_length=100, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('idanimal', models.ForeignKey(blank=True, db_column='idAnimal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.animal')),
            ],
            options={
                'db_table': 'registroproduccion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Registroalimenticio',
            fields=[
                ('idalimentacion', models.AutoField(db_column='idAlimentacion', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipoalimento', models.CharField(blank=True, db_column='tipoAlimento', max_length=100, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True)),
                ('idanimal', models.ForeignKey(blank=True, db_column='idAnimal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.animal')),
            ],
            options={
                'db_table': 'registroalimenticio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Potrero',
            fields=[
                ('idpotrero', models.AutoField(db_column='idPotrero', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('fuenteagua', models.CharField(blank=True, db_column='fuenteAgua', max_length=100, null=True)),
                ('tipopasto', models.CharField(blank=True, db_column='tipoPasto', max_length=100, null=True)),
                ('idfinca', models.ForeignKey(blank=True, db_column='idFinca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.finca')),
            ],
            options={
                'db_table': 'potrero',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MoverGanado',
            fields=[
                ('idmovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fechaevento', models.DateField(blank=True, db_column='fechaEvento', null=True)),
                ('motivo_movimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('idanimal', models.ForeignKey(blank=True, db_column='idAnimal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.animal')),
                ('idpotrero_anterior', models.ForeignKey(blank=True, db_column='idpotrero_anterior', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.potrero')),
                ('idpotrero_nuevo', models.ForeignKey(blank=True, db_column='idpotrero_nuevo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moverganado_idpotrero_nuevo_set', to='tasks.potrero')),
            ],
            options={
                'db_table': 'mover_ganado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('idinventario', models.AutoField(db_column='idInventario', primary_key=True, serialize=False)),
                ('tipoitem', models.CharField(blank=True, db_column='tipoItem', max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('unidadmedida', models.CharField(blank=True, db_column='unidadMedida', max_length=50, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('fechaultimaactualizacion', models.DateField(blank=True, db_column='fechaUltimaActualizacion', null=True)),
                ('idfinca', models.ForeignKey(blank=True, db_column='idFinca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.finca')),
            ],
            options={
                'db_table': 'inventario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='finca',
            name='cedulapropietario',
            field=models.ForeignKey(blank=True, db_column='cedulaPropietario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.propietario'),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.IntegerField(db_column='idEmpleado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('fechacontratacion', models.DateField(blank=True, db_column='fechaContratacion', null=True)),
                ('salario', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('idfinca', models.ForeignKey(blank=True, db_column='idFinca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.finca')),
                ('idhorario', models.ForeignKey(blank=True, db_column='idHorario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.horario')),
                ('usuario', models.OneToOneField(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empleado',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='idmadre',
            field=models.ForeignKey(blank=True, db_column='idMadre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.madre'),
        ),
        migrations.AddField(
            model_name='animal',
            name='idpadre',
            field=models.ForeignKey(blank=True, db_column='idPadre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.padre'),
        ),
        migrations.AddField(
            model_name='animal',
            name='idpotrero',
            field=models.ForeignKey(blank=True, db_column='idPotrero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.potrero'),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('idalerta', models.AutoField(db_column='idAlerta', primary_key=True, serialize=False)),
                ('tipoalerta', models.CharField(blank=True, db_column='tipoAlerta', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fechacreacion', models.DateField(blank=True, db_column='fechaCreacion', null=True)),
                ('fechalimite', models.DateField(blank=True, db_column='fechaLimite', null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('idfinca', models.ForeignKey(blank=True, db_column='idFinca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.finca')),
            ],
            options={
                'db_table': 'alerta',
                'managed': True,
            },
        ),
    ]
