# Generated by Django 4.2.23 on 2025-07-21 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='madre',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='moverganado',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='padre',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='potrero',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='propietario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='registroalimenticio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='registroproduccion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='registroreproduccion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='registrosalud',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='trazabilidad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
    ]
