# Generated by Django 4.2.23 on 2025-07-21 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_alerta_options_alter_animal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finca',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
