# Generated by Django 4.2.23 on 2025-07-21 03:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_finca_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='finca',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 21, 3, 26, 34, 955123, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
