# Generated by Django 4.2.23 on 2025-07-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_finca_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animali',
            fields=[
                ('idanimal', models.IntegerField(db_column='idAnimal', primary_key=True, serialize=False)),
                ('especie', models.CharField(blank=True, max_length=100, null=True)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('peso', models.CharField(blank=True, max_length=50, null=True)),
                ('fechanacimiento', models.DateField(blank=True, db_column='fechaNacimiento', null=True)),
                ('imagen', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'animali',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoteAvicola',
            fields=[
                ('idlote', models.AutoField(db_column='idLote', primary_key=True, serialize=False)),
                ('especie', models.CharField(blank=True, max_length=50, null=True)),
                ('raza', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fechaingreso', models.DateField(blank=True, db_column='fechaIngreso', null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lote_avicola',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Madrei',
            fields=[
                ('idmadre', models.IntegerField(db_column='idMadre', primary_key=True, serialize=False)),
                ('especie', models.CharField(blank=True, max_length=100, null=True)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'madrei',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Padrei',
            fields=[
                ('idpadre', models.IntegerField(db_column='idPadre', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('especie', models.CharField(blank=True, max_length=100, null=True)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'padrei',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadProductiva',
            fields=[
                ('idunidad', models.AutoField(db_column='idUnidad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipounidad', models.CharField(db_column='tipoUnidad', max_length=7)),
                ('especie_destinada', models.CharField(max_length=7)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacidad_maxima', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fuenteagua', models.CharField(blank=True, db_column='fuenteAgua', max_length=100, null=True)),
                ('tipopasto', models.CharField(blank=True, db_column='tipoPasto', max_length=100, null=True)),
                ('tipoconstruccion', models.CharField(blank=True, db_column='tipoConstruccion', max_length=100, null=True)),
                ('sistemaventilacion', models.CharField(blank=True, db_column='sistemaVentilacion', max_length=100, null=True)),
                ('sistemaalimentacion', models.CharField(blank=True, db_column='sistemaAlimentacion', max_length=100, null=True)),
                ('temperaturacontrolada', models.IntegerField(blank=True, db_column='temperaturaControlada', null=True)),
                ('iluminacion', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'unidad_productiva',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='finca',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='MoverGanado',
        ),
    ]
