# Generated by Django 4.2.23 on 2025-07-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_animali_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'managed': True},
        ),
    ]
