# Generated by Django 4.2.23 on 2025-07-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_finca_hectareas_alter_finca_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='hectareas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
